---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stress-app
  name: stress-app
  namespace: dev
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - image: kurtay/stress-app:latest
        name: stress-app
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep","5"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stress-app
  namespace: dev
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: stress-app
